# General - for sitemap
url: https://astroarena.space

# Store link
steam_store_url: https://store.steampowered.com/app/2997190/Astro_Arena/

# Social Media Links
youtube_url: https://www.youtube.com/@AstroArenaGame/videos
twitter_url: https://x.com/AstroArenaSpace
discord_url: https://discord.gg/cvMjCbMfKG
bluesky_url: https://astroarena.bsky.social

# Plugins
plugins:
  - jekyll-polyglot

# I18n
languages: ["en", "uk", "de", "es", "fr", "hi", "id", "it", "ja", "ko", "ms", "pl", "pt", "th", "tr", "vi", "zh"]
default_lang: "en"
exclude_from_localization: ["images", "styles", "CNAME", "google4c31474665a98cde.html", "favicon.ico", "robots.txt", "sitemap.xml"]
parallel_localization: false
lang_from_path: true

# Compress HTML
compress_html:
  comments: ["<!-- ", " -->"]

# Exclude from processing.
exclude:
  - ed25519
  - ed25519.pub
