# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

steam_store_url: https://store.steampowered.com/app/2997190/Astro_Arena/
youtube_url: https://www.youtube.com/@AstroArenaGame/videos
twitter_url: https://x.com/AstroArenaSpace
discord_url: https://discord.gg/cvMjCbMfKG
bluesky_url: https://astroarena.bsky.social

# Build settings
plugins:
  - jekyll-polyglot

#I18n
languages: ["en", "uk", "de", "es", "fr", "hi", "id", "it", "ja", "ko", "ms", "pl", "pt", "th", "tr", "vi", "zh"]
default_lang: "en"
exclude_from_localization: ["images", "styles", "CNAME", "google4c31474665a98cde.html", "favicon.ico", "robots.txt", "sitemap.xml"]
parallel_localization: false
lang_from_path: true

compress_html:
  comments: ["<!-- ", " -->"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - ed25519
  - ed25519.pub
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
